version: "3.5"
services:
  shell:
    build: .
    command: /bin/bash
    volumes:
      - $PWD:/ops/kube-cluster
      - $PWD/ssh:/root/.ssh
    working_dir: /ops/kube-cluster
    stdin_open: true
    tty: true

